//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.16 at 12:42:43 PM EDT 
//


package com.sigma.proto.jaxrs.rest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nooni.ws.rest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QueryResult_QNAME = new QName("http://nooni.org/ws/rest", "queryResult");
    private final static QName _Query_QNAME = new QName("http://nooni.org/ws/rest", "query");
    private final static QName _Sub_QNAME = new QName("http://nooni.org/ws/rest", "sub");
    private final static QName _Parm_QNAME = new QName("http://nooni.org/ws/rest", "parm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nooni.ws.rest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parm }
     * 
     */
    public Parm createParmType() {
        return new Parm();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSubType() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQueryType() {
        return new Query();
    }

    /**
     * Create an instance of {@link QueryResult }
     * 
     */
    public QueryResult createQueryResultType() {
        return new QueryResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nooni.org/ws/rest", name = "queryResult")
    public JAXBElement<QueryResult> createQueryResult(QueryResult value) {
        return new JAXBElement<QueryResult>(_QueryResult_QNAME, QueryResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Query }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nooni.org/ws/rest", name = "query")
    public JAXBElement<Query> createQuery(Query value) {
        return new JAXBElement<Query>(_Query_QNAME, Query.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sub }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nooni.org/ws/rest", name = "sub")
    public JAXBElement<Sub> createSub(Sub value) {
        return new JAXBElement<Sub>(_Sub_QNAME, Sub.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Parm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nooni.org/ws/rest", name = "parm")
    public JAXBElement<Parm> createParm(Parm value) {
        return new JAXBElement<Parm>(_Parm_QNAME, Parm.class, null, value);
    }

}
